name: Test Ansible playbook to bootstrap development environment

on:
  - push

jobs:
  play:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: bootstrap.yaml
          requirements: requirements.yaml
